language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ibarreche/multi-docker-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ibarreche/multi-docker-client-test npm test -- --coverage

after_success:
  - docker build -t ibarreche/multi-docker-client ./client
  - docker build -t ibarreche/multi-docker-nginx ./nginx
  - docker build -t ibarreche/multi-docker-server ./server
  - docker build -t ibarreche/multi-docker-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push ibarreche/multi-docker-client
  - docker push ibarreche/multi-docker-nginx
  - docker push ibarreche/multi-docker-server
  - docker push ibarreche/multi-docker-worker


